---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instances in Private Subnet'

Parameters:
  VpcStackName:
    Type: String
    Description: Please Insert the VPC stack name
    Default: YourVPCStackName
  
  WindowsAmiId:
    Type: String
    Description: Please provide Windows AMI ID for your region
    Default: ami-01c903856784dec6a

  LinuxsAmiId:
    Type: String
    Description: Please provide linux AMI ID for your region
    Default: ami-0aea56f3589631913


Resources:
  # Security group for the instances
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for EC2 instances
      VpcId: !ImportValue
        'Fn::Sub': '${VpcStackName}-MainVPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22  
          ToPort: 22
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - IpProtocol: '-1'  
          CidrIp: 0.0.0.0/0

  # Windows EC2 instance
  EC2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ${WindowsAmiId}  
      InstanceType: t2.micro
      SubnetId: !ImportValue
        'Fn::Sub': '${VpcStackName}-PrivateSubnet1'
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${VpcStackName}-DefaultSecurityGroup'
      Tags:
        - Key: Scheduled
          Value: "true"

# Linux EC2 instance
  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: '${LinuxsAmiId}'  
      InstanceType: t2.micro
      SubnetId: !ImportValue
        'Fn::Sub': '${VpcStackName}-PrivateSubnet1'
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${VpcStackName}-DefaultSecurityGroup'
      Tags:
        - Key: Scheduled
          Value: "true"     

 
